### ISSUE TITLE
Cannot run app on Ios 

### ISSUE THREAD

**Issue by dvijeniii05** [expo/snack#106]
**Summary**

I am trying to run an app on my device through snack.expo.io. 

But i get the following error: File 'file:/var/mobile/Containers/Data/Application/3C96BE0D-57E3-4328-80BC-41C0174C543D/Library/Caches/ExponentExperienceData/%252540git%25252Fgithub.com%25252Fdvijeniii05%25252Fcouples/snack-bundle-2-@react-navigation~stack@%5E5.5.1-ios.js -- file:///' isn't readable.

this is repository of my app: https://github.com/dvijeniii05/couples

Any ideas anyone? Would appreciate any help.

**What platform(s) does this occur on?**

iOS

**SDK Version**

v40

**Reproducible demo or steps to reproduce from a blank project**

Just trying to run the app on my device

**Comment by dvijeniii05** [comment]
Ooh and it is also constantly just keep loading firebase Resolving 'firebase-admin@^9.5.0' .. For hours and hours non stop.

**Comment by brentvatne** [comment]
snack doesn't support all react-native projects. i see that your project includes native dependencies [that are not included in the expo sdk](https://docs.expo.io/versions/latest/), like react-native-firebase. also, firebase-admin is an sdk for node.js, not react-native. snack is more similar to an [expo managed project](https://docs.expo.io/introduction/managed-vs-bare/) - it has a fixed native runtime, like a web browser.

**Comment by dvijeniii05** [comment]
Thanks for this info sir. I understand that then snack wont be any use for me. Could you suggest any other way that i could maybe test app on ios, working on Windows os ??

**Comment by brentvatne** [comment]
you could try using EAS Build to build your app for internal distribution - https://docs.expo.io/eas/

but this would get you a pretty slow feedback loop. we're working on something that could be helpful here but it's not ready yet - keep an eye out for expo development client information on https://blog.expo.io / https://twitter.com/expo
