### ISSUE TITLE
Failed to resolve dependency ( (Network request failed)

### ISSUE THREAD

**Issue by shafhad** [expo/snack#115]
### Summary

Snack is not able to load/save the dependencies 

### What platform(s) does this occur on?

Web

### SDK Version

37,38,39,40

### Reproducible demo or steps to reproduce from a blank project

Snack editor is not loading /saving the any dependencies. 

![image](https://user-images.githubusercontent.com/66770462/112975549-6c587300-9171-11eb-8121-87033ecd8df9.png)
![image](https://user-images.githubusercontent.com/66770462/112975693-96aa3080-9171-11eb-8504-dcd639cb286d.png)

**Comment by apiusage** [comment]
same issue for me as well.

**Comment by apiusage** [comment]
mine is Failed to resolve dependency 'react-native-pure-chart@*' (Network request failed)

**Comment by apiusage** [comment]
To the admin you can try importing

import { LineChart } from "react-native-chart-kit";

It will failed to resolve as well..

Previously it works fine

Please solve this issue.

**Comment by IjzerenHein** [comment]
Hi!. There seems to have been an infra problem with the Snackager service which caused these problems. The problem has been resolved by now. We are looking into why this happened and how to prevent this in the future.
