### ISSUE TITLE
Deep linking / AuthSessions don't function - "Can't make a deep link into a standalone app with no custom scheme defined"

### ISSUE THREAD

**Issue by dylmye** [expo/snack#117]
### Summary

Expo Snack features that use deep linking like AuthSessions cause Snack to throw the following error when previewing on Android and iOS:
![image](https://user-images.githubusercontent.com/7024578/114289492-446de700-9a70-11eb-9c1f-5ac259cf8bbc.png)

> Can't make a deep link into a standalone app with no custom scheme defined

This issue also occurs when opening the example on a device through the Expo Go app's project section, but not when running the same code in a newly created expo app on a computer.

### What platform(s) does this occur on?

Android, iOS

### SDK Version

40

### Reproducible demo or steps to reproduce from a blank project

https://snack.expo.io/@dylmye/reddit-auth-code - the result of clicking on the snack button [from here](https://docs.expo.io/guides/authentication/#reddit)

https://snack.expo.io/@dylmye/authsession-case-issue - one I made myself with a app.json with a schema defined

**Comment by kennethlynne** [comment]
We've also seen this. It comes from https://github.com/expo/expo/blob/35f78160a9ec1758ca73eb9e079a1c278c9b1bb1/packages/expo-linking/src/Schemes.ts#L125 - but still trying to figure out what and why it happens

**Comment by wahas-mughal** [comment]
Is there any progress on this issue? I'm facing this on expo SDK 41 after I updated the SDK from 40 to 41

**Comment by dlombardi** [comment]
Running into this now.  Seems like a pretty big issue as we can't bundle our app with linking unless this is fixed

**Comment by ceafive** [comment]
> Running into this now. Seems like a pretty big issue as we can't bundle our app with linking unless this is fixed

Hello have you been able to fix this?

**Comment by ladyshaitan** [comment]
Also stuck on this, though I'm attempting to build a staging configuration locally to troubleshoot something.  Not sure if that's correct to do even.

**Comment by tirilfjell** [comment]
Stuck on this aswell. Any solutions?

**Comment by dylmye** [comment]
cc @byCedric

**Comment by ErnestMironov** [comment]
I found a solution https://reactnavigation.org/docs/deep-linking/#setup-with-expo-projects

**Comment by AasthaSharma-git** [comment]
I am trying to implement AuthSession in snack but it gives me the same error. In the local setup the same code works well.

**Comment by rpatidar** [comment]
unrelated, i was getting the issue while starting up the app. for me the issue was the scheme and my android package name were differrent. once i fixed them. it worked.

**Comment by fedIce** [comment]
I'm getting this error only after eas building and uploading to the Play Store. when I download and launch the app it crashes. with the message "cannot deep link into standalone app with no scheme defined", but everything works fine in expo go.

**Comment by kasaiee** [comment]
> unrelated, i was getting the issue while starting up the app the app was crashing. for me the issue was the scheme and my android package name were differrent. once i fixed them. it worked.

I have exactly the same error. can you explain how to do this, please?

**Comment by mercpls** [comment]
> unrelated, i was getting the issue while starting up the app the app was crashing. for me the issue was the scheme and my android package name were differrent. once i fixed them. it worked.

I'm just curious how this could possibly be a solution for an iOS crash? My understanding is that package name does NOT have to be the same as the scheme. Unless I am wrong here?

**Comment by TomHiller-swd** [comment]
I am not sure if this will help anyone else but we had a bug that closely resembled this issue with the consistent error was 
> Cannot make a deep link into a standalone app with no custom scheme defined

Even though a scheme was defined.  The problem was caused by importing and calling `react-navigation` libraries while also using `expo-router`.   For us, it was easier to remove `expo-router` but as long as the correct libraries are called in conjunction with each other, this may someone else.

**Comment by hanyaonian** [comment]
> react-navigation



> > unrelated, i was getting the issue while starting up the app the app was crashing. for me the issue was the scheme and my android package name were differrent. once i fixed them. it worked.
> 
> I have exactly the same error. can you explain how to do this, please?

hi, same here. did you fix it at lats?

**Comment by Neiso** [comment]
Got this error only on production build. I removed expo-linking for now as I was not using it yet and builds are now working properly.

**Comment by GabrielDierks** [comment]
Same error with Expo SDK 51, expo router on iOS, caught by Sentry on prod.

"Cannot make a deep link into a standalone app with no custom scheme defined"

**Comment by dKally** [comment]
> Same error with Expo SDK 51, expo router on iOS, caught by Sentry on prod.
> 
> "Cannot make a deep link into a standalone app with no custom scheme defined"

I did this to fix this error  on my project


on app.json:

{
  "expo": {
    ...
    "scheme": "my-project-name",
    ...
}


and where I use the "Linking" I did like that

      const linking = {
        prefixes: [Linking.createURL('/'), 'my-project-name://'],
      }

      const redirectUrl = linking
      const oAuthFlow = await googleOAuth.startOAuthFlow({ redirectUrl })

**Comment by xsjk2023** [comment]
Encountered same error in production apk build (prebuild) expo 51.
However after `cd ./android ;; ./gradlew clean ; cd ..`  , the apk can open normally.

Problem encounter previously
```
cd ./android ; ./gradlew app:assembleRelease; cd ..

# adb logcat
Cannot make a deep link into a standalone app with no custom scheme defined, js engine: hermes
```
