### ISSUE TITLE
AsyncStorage.setItem is not a function, despite installing react-native-async-storage

### ISSUE THREAD

**Issue by peterpme** [expo/snack#135]
### Summary

AsyncStorage.setItem is not a function

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version

41

### Reproducible demo or steps to reproduce from a blank project

```
import * as AsyncStorage from '@react-native-async-storage/async-storage';
AsyncStorage.setItem('hi', 'hello');
```

https://snack.expo.io/@peterpme/humiliated-cake

**Comment by peterpme** [comment]
Oh wait, if I import it as `import AsyncStorage ...` it works, the wildcard import is breaking it

**Comment by brentvatne** [comment]
looks like `import AsyncStorage` is correct as per docs: https://react-native-async-storage.github.io/async-storage/docs/usage/#importing
