### ISSUE TITLE
Access to origin forbidden

### ISSUE THREAD

**Issue by esdu-weptile** [expo/snack#148]
I have React.js project which I want to show expo app as preview via iframe on it. Everything works well in localhost but remote. When I enabled verbose getting `Access to origin "https://dev.admin.woo2app.com is forbidden` on browser console.. I enabled CORS bu by adding header add to .htaccess and I checked it by https://www.test-cors.org/ it looks like working. I also tried [firefox extension](https://addons.mozilla.org/en-US/firefox/addon/cors-everywhere/)  but same.

What platform(s) does this occur on?
Web

SDK Version
40

**Comment by IjzerenHein** [comment]
Hi, please provide a code example or link on how you are trying to use Snack inside an iframe.

**Comment by esdu-weptile** [comment]
Here is link which created by snack: https://snack-web-player.s3.us-west-1.amazonaws.com/v2/41/index.html?initialUrl=exp%3A%2F%2Fexp.host%2F%40snack%2Fsdk.41.0.0-Ll9QCQTRfY&origin=https%3A%2F%2Fdev.admin.woo2app.com&verbose=true

**Comment by Tozare** [comment]
Hi, I have the same problem. Did you manage to fix it?

**Comment by esdu-weptile** [comment]
Unfortunately not.

**Comment by esdu-weptile** [comment]
While I was checking scripts which loaded by expo snack I saw there is origin control in https://snack-web-player.s3.us-west-1.amazonaws.com/v2/41/static/js/app.4eadea48.chunk.js. 

Unminified code:
```js
 var W = { id: P.default.installationId, name: P.default.deviceName, platform: S.a.OS },
    $ = [],
    H = [
        "https://snack.expo.io",
        "https://staging.snack.expo.io",
        "https://snack.expo.dev",
        "https://staging.snack.expo.dev",
        "http://snack.expo.test",
        "https://snack.expo.test",
        "https://build.draftbit.com",
        "https://build.stagingbit.com",
        "https://codecademy.com",
        "https://www.codecademy.com",
        "https://jackdaw.codecademy.com",
        "https://staging.codecademy.com",
        "https://production.codecademy.com",
    ];
function G(e) {
    return H.includes(e) || e.startsWith("http://localhost:");
}
var X = window !== window.parent ? window.parent : window.opener,
    V = null != (M = new URL(document.URL).searchParams.get("origin")) ? M : "";
V || q.b("No origin provider in the URL");
var Z = G(V) ? V : void 0;
Z || q.b('Access to origin "' + V + " is forbidden");
```
It looks like this package works only on localhost and some lucky sites.
Is there any way to bypass it or we should give up?

**Comment by IjzerenHein** [comment]
Hey guys! Sorry for now getting back to you sooner.
At the moment we only allow certain partners to use the Snack web-player directly. This was done to prevent random sites from excessively using our Snack services and running up server costs (and possible degrading the service). In the future we plan to associate this kind of service usage with your EAS account. Depending on usage we might bill you for the server usage.

If you are interesting in using the Snack web-player please let us know and tell us how you would like to use it, so we can discuss it internally.

best regards
