### ISSUE TITLE
error when import snack project from github

### ISSUE THREAD

**Issue by saeedjafary** [expo/snack#19]
when i try to use Import git repository in snack to edit my react native project this error is displayed : An error occurred during import. This could be because the data provided was invalid, or because the repository referenced is not a properly formatted Expo project.

my github link is : https://github.com/saeedjafary/SarvShop

I am seeing this error recently. there was no problem before

**Comment by IjzerenHein** [comment]
Duplicate of #54

**Comment by ashim1588** [comment]
Same Issue here
