### ISSUE TITLE
Remove query params on save

### ISSUE THREAD

**Issue by brentvatne** [expo/snack#22]
I think it's common for people to want to open an example from, for example, the react-navigation or Expo docs, then make a few changes, hit save, and share that link.

If you go to https://reactnavigation.org/docs/header-buttons#customizing-the-back-button and press "Try the "header interaction" example on Snack" then hit save, when you copy the URL you will see something like this:

https://snack.expo.io/@notbrent/header-interaction?platform=android&name=header%20interaction&dependencies=%40react-native-community%2Fmasked-view%40%5E0.1.7%2C%40react-navigation%2Fbottom-tabs%40%5E5.7.0%2C%40react-navigation%2Fdrawer%40%5E5.8.5%2C%40react-navigation%2Fmaterial-bottom-tabs%40%5E5.2.13%2C%40react-navigation%2Fmaterial-top-tabs%40%5E5.2.13%2C%40react-navigation%2Fnative%40%5E5.7.0%2C%40react-navigation%2Fstack%40%5E5.7.0%2Creact-native-paper%40%5E3.10.1%2Creact-native-reanimated%40%5E1.7.0%2Creact-native-safe-area-context%40%5E3.0.2%2Creact-native-screens%40%5E2.9.0%2Creact-native-tab-view%40%5E2.14.0&sourceUrl=https%3A%2F%2Freactnavigation.org%2Fexamples%2F5.x%2Fheader-interaction.js

We can probably remove all of those query params on save.

**Comment by IjzerenHein** [comment]
This feature has been implemented and can be triggered by setting `&hideQueryParams=true` in the URL 👍
