### ISSUE TITLE
ThemeProvider is not working for external packages.

### ISSUE THREAD

**Issue by sangameshsomawar** [expo/snack#238]
### Summary

I created a component library on top of `styled-components`.
Library: https://github.com/sangameshsomawar/test
Npm: https://www.npmjs.com/package/@sangameshsomawar/test

When I install the library in any new react-native project or expo project, the theme is getting passed correctly to the external package, and colors are properly rendered.  But when I test the same code in snack, the theme is not working. This issue is only happening in the snack.

Please find below snack examples:

|Output when Typography Component is written directly in snack| Output when Typography code is fetched from the [library](https://github.com/sangameshsomawar/test/tree/master/lib) and then referred in snack|
|---|---|
| Snack Link:https://snack.expo.dev/@sangamesh.somawar/typography | Snack Link: https://snack.expo.dev/@sangamesh.somawar/typography2|
|<img width="336" alt="Screenshot 2021-12-07 at 1 09 23 PM" src="https://user-images.githubusercontent.com/93119254/144986790-ef75334a-186d-4198-8751-21c646ea0e8a.png"> |  <img width="326" alt="Screenshot 2021-12-07 at 1 09 37 PM" src="https://user-images.githubusercontent.com/93119254/144986795-1063a162-b78f-416b-ac89-5bce53d11430.png"> |

I think [context](https://stackoverflow.com/questions/57976672/react-context-api-not-working-from-custom-npm-component-library) is not getting passed correctly in the snack.

### What platform(s) does this occur on?

Android, iOS, Web

### Reproducible demo or steps to reproduce from a blank project

see above

**Comment by sangameshsomawar** [comment]
@IjzerenHein Please Help.

**Comment by byCedric** [comment]
Hi @sangameshsomawar, your library is a full bare react native app. It contains another react native instance which is causing issues here. If you want to add this lib to your project in Snack, you have to create a package with just the JS files you want, not the whole app. (e.g. only the files in `lib`)

Hope this helps.

**Comment by sangameshsomawar** [comment]
@byCedric: I have tried that as well. Let me create a snack example with that approach. I will share it with you here.
