### ISSUE TITLE
Reanimated 2.3+ is crashing on Snack

### ISSUE THREAD

**Issue by byCedric** [expo/snack#245]
### Summary

Reanimated is crashing apps on SDK 44. Might have been [related to the changes in the plugin](https://github.com/expo/snack/blob/097e2dae39dd655910c16669a12cf25e916049f6/runtime/patches/react-native-reanimated%2B2.3.1.patch): 

```
_stopObservingProgress is not defined
  Evaluating react-native-reanimated.js
  Evaluating App.js
  Loading App.js
ReferenceError: _stopObservingProgress is not defined
    at Object.defineProperty.value (react-native-reanimated.js:3:144722)
    at n (react-native-reanimated.js:3:436754)
    at Object.eval (react-native-reanimated.js:3:95149)
    at n (react-native-reanimated.js:3:436754)
    at Object.eval (react-native-reanimated.js:3:119689)
    at n (react-native-reanimated.js:3:436754)
    at eval (react-native-reanimated.js:3:437029)
    at eval (react-native-reanimated.js:3:437073)
    at Object.eval (react-native-reanimated.js:3:437079)
    at eval (react-native-reanimated.js:8:4)
```

### What platform(s) does this occur on?

Android

### SDK Version

44

### Reproducible demo or steps to reproduce from a blank project

https://staging.snack.expo.dev/@bycedrictest/reanimated-sdk44

**Comment by nandorojo** [comment]
Is there anyone from reanimated who may know how to fix this?

**Comment by Simek** [comment]
Let me add the few more details about this issue, which emerged when I have tried to fix this:
* bundle with Reanimated `2.3.0`+ is affected (including `2.4.0/1`), `2.2.x` works as expected, so the problem lies in the new `LayoutAnimation` feature code
* I was thought that some of the global type declaration might be missing in `gloabl.d.ts`, but after altering the code locally and rebundling Reanimated for Snack my change doesn't help with the issue, see (https://github.com/software-mansion/react-native-reanimated/pull/2137/files#diff-5206c097f5448ac0c731d4f9a39c2009cbc2bfad890e5d6f09b82a609518ad6e)
* I have also verified that bundle minification/optimization on the Snackager side is not a problem, same problem occurred without this bundle features turned on

**Comment by piaskowyk** [comment]
Hey Did someone be able to reproduce this issue locally? Because I have just checked android and iOS with Expo 44 and everything works. I want to solve this issue but I am not able to reproduce it 😕

**Comment by Simek** [comment]
> Hey Did someone be able to reproduce this issue locally? 

Hey @piaskowyk, yes, but you need to run the Snack website, bundler (Snackager) and proxies locally from this repo (or you can check the Snack link posted by Cedrick). 

This issue do not affect the Expo projects, only running using Reanimated 2.3+ inside Snack project is a problem. The difference between those environments is that Expo uses package from NPM, when Snack relies on the bundler which fetches package from NPM, and then processes all the dependencies packing them into bundles for each platform.

**Comment by Simek** [comment]
Also it looks like the title is misleading a bit, Expo SDK doesn't matter there, same issue occurs on SDK 43, when using Reanimated  `2.3.0`+. The only difference is that SDK 44 bundles the problematic version (`2.3.1`) as default one:
* https://snack.expo.dev/@simek/rebellious-tea

**Comment by piaskowyk** [comment]
Ok, so I will try to set up the Snack website on my computer. 
Do you know why [this patch](https://github.com/expo/snack/blob/097e2dae39dd655910c16669a12cf25e916049f6/runtime/patches/react-native-reanimated%2B2.3.1.patch) is required?

**Comment by Simek** [comment]
> Ok, so I will try to set up the Snack website on my computer. 

`yarn && yarn start` in root should be enough in this case IIRC.

> Do you know why [this patch](https://github.com/expo/snack/blob/097e2dae39dd655910c16669a12cf25e916049f6/runtime/patches/react-native-reanimated%2B2.3.1.patch) is required?

Sorry, nope, but we can ask @byCedric. 🙂

**Comment by piaskowyk** [comment]
Thanks! I will notify you about the progress.

**Comment by danstepanov** [comment]
@byCedric can this be closed?
