### ISSUE TITLE
Snack fails to parse largeish JSON blobs

### ISSUE THREAD

**Issue by anp** [expo/snack#25]
https://snack.expo.io/S1dlGkiMG

Running on iOS Appetize. Expected behavior works with 3 items fetched from the API, change line 16 to false to see what happens with a larger response body. @brentvatne pointed out that if you skip parsing the JSON and just print the length of the response body, it succeeds, so it seems like it's hanging on `await resp.json()`.

**Comment by IjzerenHein** [comment]
I was unable to reproduce this. It briefly shows null but that's because takes a long time. After that the contents is displayed correctly. Closing
