### ISSUE TITLE
Access to origin forbidden 

### ISSUE THREAD

**Issue by Tozare** [expo/snack#255]
### Summary

Hi,

You have recently added "https://app.sizze.io/" domain to your allowed domains for using web preview feature. However, it is still gives "Access to origin forbidden". I suppose that you have to release a version with this code so that we could reinstall snack-sdk and fix the error. Am I right or is this not the error?

Thank you in advance!

Best regards,
Sizze Team

### What platform(s) does this occur on?

Web

### SDK Version

40-42

### Reproducible demo or steps to reproduce from a blank project

can not be reproduced

**Comment by byCedric** [comment]
Should be resolved 😄
