### ISSUE TITLE
Failed to resolve dependency 'react-native-maps@0.29.4'

### ISSUE THREAD

**Issue by wodin** [expo/snack#279]
### Summary

Snack is unable to resolve `react-native-maps@0.29.4`

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version

41, 42, 43, 44

### Reproducible demo or steps to reproduce from a blank project

Go to https://snack.expo.dev

Add the following import to the default snack:

```
import MapView from 'react-native-maps';
```

Click on the Add Dependency button.

It takes quite a while to try to resolve the package. Then it fails with the following error:

```
package.json (3:5)Failed to resolve dependency 'react-native-maps@0.29.4' (Module not found: Error: Package path ./unstable-native-dependencies is not exported from package /tmp/snackager/snackager/buildStatus/1/react-native-maps@0.29.4-ios,android,web/package/node_modules/react-dom (see exports field in /tmp/snackager/snackager/buildStatus/1/react-native-maps@0.29.4-ios,android,web/package/node_modules/react-dom/package.json)
```

**Comment by wodin** [comment]
I initially thought the error was the same for the different SDK versions, but I've checked again and here's what I've found:

SDK 41 does resolve, but doesn't work:
```
App.js (3:8372)U is undefined (Device)

  Evaluating module://react-native-maps.js
  Evaluating module://App.js.js
  Loading module://App.js
```

SDK 42, doesn't resolve, but the error is different:
```
App.js (1:8372)Unable to fetch module snackager-1/react-native-maps@0.28.0 for web. (Device)
```

SDK 43, same as SDK 44 except for the version number:
```
package.json (6:5)Failed to resolve dependency 'react-native-maps@0.28.1' (Module not found: Error: Package path ./unstable-native-dependencies is not exported from package /tmp/snackager/snackager/buildStatus/1/react-native-maps@0.28.1-ios,android,web/package/node_modules/react-dom (see exports field in /tmp/snackager/snackager/buildStatus/1/react-native-maps@0.28.1-ios,android,web/package/node_modules/react-dom/package.json)
```

**Comment by szabodanika** [comment]
I'm having the same issue, neither of the SDK versions can resolve the dependency

**Comment by byCedric** [comment]
Fixed by https://github.com/expo/snack/pull/283, will deploy after CI turns green!

**Comment by byCedric** [comment]
Done and deployed.

**Comment by elzen20** [comment]
I couldn't follow up what you have done to solve this issue. I am working on Snack, I would like to fix this issue.

**Comment by wodin** [comment]
@elzen20 what problem are you seeing?

If I create a new Snack, I can add `react-native-maps` as a dependency without errors now.
