### ISSUE TITLE
I seem to be unable to access snack using any browser on a Mac

### ISSUE THREAD

**Issue by onereg-dan** [expo/snack#306]
### Summary

Whenever I try to load snack in a browser (any examples on any pages) it just hangs and loads forever. I've tried resetting my browser, resetting the cache, re-installing chrome, flushing the DNS, restarting and updating the computer with no luck. I've also tried resetting the router and changing my IP.

<img width="1257" alt="image" src="https://user-images.githubusercontent.com/106371728/170647835-99b61a10-47e4-4791-b7a6-91f2ac8a3fe3.png">

Above is the javascript error that is coming up. 
OS: macOS 12.4

I can confirm another user with the same spec device but different networks and location is having issues as well

### What platform(s) does this occur on?

Web

### SDK Version

Any examples on any react native pages or just loading snack in general

### Reproducible demo or steps to reproduce from a blank project

Going to https://snack.expo.dev/ or any other page with snack examples on it

**Comment by RichardLudwig** [comment]
I'm having the same issue. How did you solve the problem?
