### ISSUE TITLE
Always continues in `Resolving`

### ISSUE THREAD

**Issue by brunomacedo** [expo/snack#308]
### Summary

I'm trying to install in **[Expo Snack](https://snack.expo.dev/)**, but it doesn't work. I couldn't find the error. 
It always continues in `Resolving`

```
Resolving 'phosphor-react-native@*' ...Dependencies
```

<img alt="image" src="https://user-images.githubusercontent.com/10273138/173129186-c44c1e2a-f5ff-49f2-b2f3-b844af596a98.png">

### What platform(s) does this occur on?

iOS

### SDK Version

45

### Reproducible demo or steps to reproduce from a blank project

Add the dependency "phosphor-react-native".
There are others dependencies are not working too, but this one is an example.

**Comment by byCedric** [comment]
Hi! I validated that Snack can bundle `phosphor-react-native`, you can see this here: https://github.com/expo/snack/runs/7412791546?check_suite_focus=true#step:6:258. It did take >5min to bundle it, but eventually, it should go through. Once it's built, it's cached and should be available immediately.
