### ISSUE TITLE
How to use dependencies in private registry?

### ISSUE THREAD

**Issue by rainysir** [expo/snack#309]
Summary
I want to use Snack for component preview, I'm trying to add new dependencies  in [Expo Snack](https://snack.expo.dev/), but dependencies in private registry.
Is there any solution to this please?

What platform(s) does this occur on?
*
SDK Version
*

**Comment by byCedric** [comment]
Hi! Unfortunately, we don't support private registries and have no plans to add support. Feel free to publish the dependency to npm to use it inside Snack!
