### ISSUE TITLE
Typo in the description text for the "Save your snack" dialog.

### ISSUE THREAD

**Issue by kishannareshpal** [expo/snack#340]
### Summary

Opening a snack while not logged in and modifying it then pressing save or pressing <strong><key>Cmd<key> or <key>Ctrl<key> + <key>S<key></strong>, will show an alert like the image attached, with a typo in it's description.

The second sentence says <strong>`Every time you save, your will get...`</strong>, instead it should be <strong>`.. you will get...`</strong>. Notice the typo in the word `your` that needs changing to `you`, unless you meant to say `your snack`, in that case, the word `snack` is missing :)

<img width="200" alt="Screenshot 2022-07-29 at 18 03 10" src="https://user-images.githubusercontent.com/25407841/181809837-df4fed59-4826-4584-8f9a-43cef9db50ed.png">

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version

v44.0.0

### Reproducible demo or steps to reproduce from a blank project

1. Open any snack while not being logged in.
2. Modify it, by typing anything
3. Attempt to save the snack
4. A popup titled "Save your snack" will get displayed

**Comment by Sinha1994** [comment]
@byCedric I would like to take this up, please assign it to me.

**Comment by byCedric** [comment]
Heads up, deployments are blocked until Expo SDK 46 is released :) Hopefully somewhere next week.

**Comment by byCedric** [comment]
Done! This has been rolled out to production now! Thanks @kishannareshpal and @Sinha1994 ❤️
