### ISSUE TITLE
Paid Appetize account cannot seem to be used

### ISSUE THREAD

**Issue by Salet** [expo/snack#362]
### Summary

Hey, we aim to embed Snack snippets in our product's documentation and I'm currently looking for a way to bypass queues when previewing the apps on Appetize Android/iOS emulators.

I couldn't find any information about connecting a paid Appetize subscription (which should enable that) with Snack, so I started by asking around on Discord. Turned out there's an undocumented option to pass `appetizePayerCode` to Snack embeds. I can see it's referenced in several places in [the code](https://github.com/expo/snack/search?q=appetizePayerCode).

The next challenge was to generate said payer code on Appetize's admin dashboard, as I couldn't find it anywhere. I contacted their support and there's an undocumented page that isn't linked to by anything, hidden [here](https://appetize.io/payer-code). I was able to generate the code as we already have a Basic subscription.

Now I'm testing passing the code in my snack embeds, and I can see the option is passed to the Snack's iframe URL. However, the account doesn't seem to be used at all. There's still a preview queue and I don't have any usage noted on our Appetize account. Is this option still supported?

### What platform(s) does this occur on?

Android, iOS

### Reproducible demo or steps to reproduce from a blank project

1. Subscribe for a paid Appetize account and generate a payer code here: https://appetize.io/payer-code
2. Create an Expo Snack snippet with any sort of valid code and save it
3. Use the Snack embed code to place it on a website. Pass the payer code to `data-snack-appetize-payer-code` attribute
4. Load the embed on the website and turn on the app preview on either iOS or Android
5. There's still a waiting queue

**Comment by mattjennings** [comment]
Hey @Salet, I'm a software engineer at Appetize. I looked into this and it was an issue on our side. It should be resolved now. Apologies for the inconveniences. 

We are also going to improve our documentation re: Payer Codes.

**Comment by Salet** [comment]
Thanks @mattjennings, I tested again and the option seems to be working correctly now. Much appreciated.

Perhaps the `appetizePayerCode` could be added to Snack docs as well. However, it wasn't the point of this issue and so I'm closing it for now.
