### ISSUE TITLE
problems regarding access denied

### ISSUE THREAD

**Issue by fatikhul36** [expo/snack#409]
### Summary

wherever i navigate to my page,it has this message shown in my web preview : AccessDeniedAccess DeniedZHFDGHG5705WNYASt2Ip9BvQNtrZVFoTVBcc+dthOewyHAdMc0lunmMNHWxwGIcI1lSo0CrFWnCfe5ptVl7uAAcHbBM=
and im stuck to correct page in expo go after few reload

### What platform(s) does this occur on?

Web

### SDK Version

v47.0.0

### Reproducible demo or steps to reproduce from a blank project

i dont know. it happens

**Comment by Kudo** [comment]
hi there! could you share the snack url you tested?

**Comment by fatikhul36** [comment]
sorry, its already fixed.
turns out i forgot to place {navigation} in props.
sorry for the inconvinient

Pada tanggal Sen, 3 Apr 2023 08.45, Kudo Chien ***@***.***>
menulis:

**Comment by Kudo** [comment]
cool, i'm going to close this issue. if there's any other problems, please create a new issue for us. thanks!
