### ISSUE TITLE
error when import snack project from github

### ISSUE THREAD

**Issue by saeedjafary** [expo/snack#54]
when i try to use Import git repository in snack this error is displayed : An error occurred during import. This could be because the data provided was invalid, or because the repository referenced is not a properly formatted Expo project.

my public github link is : https://github.com/saeedjafary/SarvShop

I am seeing this error recently. there was no problem before

**Comment by IjzerenHein** [comment]
Hi! This issue has been resolved, import of both mentioned repositories now works as expected 👍
