### ISSUE TITLE
PropType Validation Bug

### ISSUE THREAD

**Issue by alishehzad2017** [expo/snack#56]
I originally created this issue on the expo repository and a Samaritan who goes by _wodin_ said it would be better moving it to this repository.

The issue I have been experiencing is not seeing a yellow warning box on snack when I pass an incorrect Proptype.

Below is the link to the snack that demonstrates the problem:
https://snack.expo.io/@alishehzad/no-warning-for-incorrect-proptype

Here _**count**_ is validated in 'Count.js' and exported to 'App.js'.

This works fine locally. Just not in a snack.

**Comment by IjzerenHein** [comment]
Duplicate of #18
