### ISSUE TITLE
"Use a free Appetize.io account" is missleading - since it's not free (anymore?)

### ISSUE THREAD

**Issue by SelfDevTV** [expo/snack#58]
Hi guys,

I just wanted to point out the message while you wait for your loading Android or iOS App in the expo snack.

It says this:

>Device preview is at capacity
>Queue position: 23
>Don't want to wait?
>Use a free Appetize.io account

But when I create an Appetize account it says that I have to pay.

So either it's not free anymore or I got something wrong?

**Comment by byCedric** [comment]
[We've changed this to](https://github.com/expo/snack/blob/1c7fd0eb8c9073fb590767da2a6103a78c1081b2/website/src/client/components/DevicePreview/AppetizeFrame.tsx#L320): 
![Screenshot 2021-06-01 at 19 21 46](https://user-images.githubusercontent.com/1203991/120365408-b0512b00-c30e-11eb-8d34-a85165f0447e.png)
