### ISSUE TITLE
snack-sdk does not support SDK 51

### ISSUE THREAD

**Issue by biadars** [expo/snack#585]
### Summary

The Expo Go iOS and Android apps now support SDK 51 exclusively, and cannot be downgraded. snack-sdk only supports SDK versions 48.0.0, 49.0.0, and 50.0.0 (see definition of SDKVersion in snack-content/build/sdks/types.d.ts). This means that if you download and install the latest version of Expo Go, you are locked out of running a snack generated via snack-sdk on your device.

Expected behaviour:

- Create Snack via snack-sdk
- Scan QR code with mobile device
- Successfully run snack on device

Actual behaviour:
- Create Snack via snack-sdk
- Scan QR code with mobile device
- Receive error message - Snack targets SDK 50 but installed Expo Go only supports SDK 51

### What platform(s) does this occur on?

Android, iOS

### SDK Version

51

### Reproducible demo or steps to reproduce from a blank project

1. Create any Snack via snack-sdk
2. Install latest version of Expo Go on a mobile device
3. Scan QR code from snack

**Comment by biadars** [comment]
Actually it looks like this was addressed by https://github.com/expo/snack/pull/577 (thanks @byCedric!). Any idea when this could be published? I'm working on a project using snack-sdk that's now broken until the next update

**Comment by byCedric** [comment]
Hi @biadars! We've just published `snack-sdk@6.0.0` (had to bump the major version due to incorrect nested dependency constraints). This supports SDK 51!

Let me know if anything doesn't work for you

**Comment by biadars** [comment]
That was super quick! I've upgraded to the latest version and everything's working again, thanks for the swift fix 🙏
