### ISSUE TITLE
Importing GitHub repository which uses the `main` branch fails

### ISSUE THREAD

**Issue by tiavina-mika** [expo/snack#61]
![image](https://user-images.githubusercontent.com/42656064/99178766-927ff800-2727-11eb-9077-571e934aa7a0.png)

when i try to use Import git repository in snack to edit my react native project this error is displayed : 
`An error occurred during import. This could be because the data provided was invalid, or because the repository referenced is not a properly formatted Expo project.`

**Comment by IjzerenHein** [comment]
Hi! Thanks for reporting this. This seems to happen when importing new repositories  which use `main` as the default branch, instead of the old `master`.

**Comment by IjzerenHein** [comment]
Until we get this fixed, you can workaround this problem by explicitly setting the branch name to `main`

![image](https://user-images.githubusercontent.com/6184593/107224059-3b807b00-6a17-11eb-8739-ebb1a85a0134.png)

**Comment by IjzerenHein** [comment]
We've rolled out the fix. Importing a git repo which uses the `main` branch now works 👍

**Comment by Jaysalasi** [comment]
it does not work anymore.

![image](https://github.com/expo/snack/assets/46465079/b1f633a0-9cc5-4f35-8faa-ee926219db52)

**Comment by IjzerenHein** [comment]
When I try to access the url: https://github.com/Jaysalasi/digiyo, it doesn't work.

Are you sure that repo exists and is not private? @Jaysalasi

**Comment by Jaysalasi** [comment]
It was public when I tried importing after it didn’t work I made it private again. You can try it now I’ve made the repo public again

**Comment by Ali-Aref** [comment]
+1 same issue. can not import my github expo project to snack.
the project structure is correct and matches the expo projects and also the repo is pubic. 

any solution?

**Comment by ashim1588** [comment]
+1 same issue here
cannot import my github project
